import type { Metadata } from 'next'
import './globals.css'
import { TooltipProvider } from '@/components/ui/tooltip'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { Header } from '@/components/layouts'
import { SiteFooter } from '@/components/layouts/footer'

export const metadata: Metadata = {
  title: '@duck-pdf',
  description: 'Duck PDF generated by wildduck (ahmedayoub): https://github.com/wildduck2',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <TooltipProvider>
          <div className="min-h-screen gap-16 font-[family-name:var(--font-geist-sans)]">
            <Header />
            {children}
            <SiteFooter />
          </div>
        </TooltipProvider>
      </body>
    </html>
  )
}
